apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    cluster-announce-hostname redis-cluster
    cluster-announce-port 6379
    cluster-announce-bus-port 16379
    cluster-announce-ip ${POD_NAME}.redis-cluster